### ISSUE TITLE
Allow negative times to be used in fragment begin times

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#109]
Use case:  

Subtitles files may be created separately from video and audio for any particular piece of content.  Subtitles may be created in different facilities and at different points in time than the original content.  As a result of this decoupling, sometimes the subtitles file will use a different start time than the video and audio.  

Proposal:  

Time expressions in sub-elements are relative to the time expressions in their parent elements, as described in section 10.2.4 of the TTML specification.

When subtitles have non-zero start times relative to the video they are to be synchronized with, the parent div element can have an offset in the begin attribute which, when applied to the times in the samples within the div element, will produce time expressions that synchronize with video.

The following example uses this offset to indicate that the titles are using start time of 01:00:00:00, and require adjustment before their values express the actual time they should appear in the video.

```
<div begin="-01:00:00:00">
   <p begin="01:00:05:00" end="01:00:10:00">
   This text should appear at 00:00:05:00
   </p>
</div>
```

(raised by Courtney Kennedy on 2014-08-14)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/335

**Comment by nigelmegitt** [comment]
The tracker issue conversation indicates that this was not agreed by all.

I would prefer to close this as "wontfix" because any media timeline offsetting should be part of the document processing context and *not* part of the TTML document. Otherwise the situation is confusing and it will not be obvious to packagers if the effective offset should be carried through from the TTML, does not need to be duplicated, or needs to be taken into account when calculating and applying any other offset.

My preferred option here is something more similar to #125 or even more simply, a named metadata item that indicates the coordinate in the document's timeline when the related media begins.

**Comment by palemieux** [comment]
>I would prefer to close this as "wontfix" because any media timeline offsetting should
> be part of the document processing context and not part of the TTML document. 

+1

> a named metadata item that indicates the coordinate in the document's timeline
> when the related media begins.

... at time of authoring, right?

[Doesn't this mean in practice capturing the timecode address, if any, of the first frame of the related media objects at authoring?]

**Comment by nigelmegitt** [comment]
> ... at time of authoring, right?

Exactly.

The related media object may or may not use timecode - we can't know the right time expression to use in an external object of an unknown format, so this has to be a value relative to the document's timeline, and in the document's timebase.

The two timebases where I think this could be most useful are `smpte` and `clock` - the latter would be useful for creating an archive of live subtitles.

**Comment by nigelmegitt** [comment]
As per the discussion above, marking this as to close since the majority opinion seems to prefer "wontfix".

**Comment by nigelmegitt** [comment]
[Meeting 2016-12-22] Agreed to close.
