### ISSUE TITLE
"Absolutize" has no defined meaning in relation to URL.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#1150]
> RFC 3986 does not define "absolutizing". I think you might mean "resolving a reference as defined in RFC 3986".

_Originally posted by @palemieux in https://github.com/w3c/ttml2/pull/1054/files_

The term "absolutizing" is used 9 times in TTML2 - this should be editorially fixed for clarity.

**Comment by skynavga** [comment]
Is it truly necessary to define every word used? What can one possibly mean by _absolutize_ in the context of URLs that doesn't mean _resolve a relative URI into an absolute URI_, and why is it necessary to add a definition for such an obvious and only reasonable interpretation?

**Comment by palemieux** [comment]
> Is it truly necessary to define every word used? 

@skynavga No. In this case, it is in fact misleading (and unnecessary) to invent a new word (_absolutize_) since the normative reference already provides an unambiguous hook: _resolving a reference as defined in RFC 3986_

**Comment by skynavga** [comment]
@palemieux well, I can't claim to have invented it, since there are so many references to "absolutize URL" that one can find online, such as [here](https://books.google.com.ph/books?id=Gp4chqpT4vkC&pg=PA144&lpg=PA144&dq=absolutize+url&source=bl&ots=au5IEYnzLZ&sig=ACfU3U2DDEHpXk_O4GbKXaYoGwxv8S2dSA&hl=en&sa=X&ved=2ahUKEwi7v-musLPkAhXoxYsBHWf4A5A4ChDoATABegQICBAB#v=onepage&q=absolutize%20url&f=false) and [also here](https://books.google.com.ph/books?id=1Cp2-ydxKj4C&pg=PA97&lpg=PA97&dq=absolutize+url&source=bl&ots=FH-UmDFNwc&sig=ACfU3U1MyIGJyLfrsfA97pDutB8FyJO5xg&hl=en&sa=X&ved=2ahUKEwi7v-musLPkAhXoxYsBHWf4A5A4ChDoATADegQICRAB#v=onepage&q=absolutize%20url&f=false) from 2002, and [again here](https://grack.com/blog/2009/11/17/absolutizing-url-in-javascript/) from 2009, etc

**Comment by palemieux** [comment]
I never suggested you did, only that TTML2 should not use it :)
