### ISSUE TITLE
Use of content encoding

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#124]
Add recommendation that a server should transfer TTML resources using the gzip content encoding if client indicates support for that client encoding.

(raised by Glenn Adams on 2015-01-01)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/360

**Comment by nigelmegitt** [comment]
I support the general intent here, however since we do not specify and content delivery mechanism and have done no work to investigate compression standards in terms of effectiveness, perhaps we should remain silent on the matter? 

By the way HTTP compression already widely uses gzip without us having to state anything.

**Comment by nigelmegitt** [comment]
[Meeting 2016-12-22] Agreed to close.
