### ISSUE TITLE
Use of offset-time expression in smpte mode

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#160]
Need to address semantics of using an offset-time expression, e.g., 543t, 692.3f, etc, when time base is smpte continuous mode.

[1] http://w3c.github.io/ttml2/spec/ttml2.html#time-expression-semantics-smpte

**Comment by nigelmegitt** [comment]
This is partially related also to #105.

**Comment by skynavga** [comment]
Works for me. Closing as I am not aware of any specific semantic issue here. If so desired, you may specify draft text to be added and re-open this issue.

**Comment by nigelmegitt** [comment]
I believe the problem here, in advance of drafting a solution, is that it is possible to specify offset times that do not evaluate to integer frame values, and there is no guidance on what this means and what should be done. Specifically,

> S = (countedFrames - droppedFrames + (subFrames / subFrameRate)) / effectiveFrameRate 
>
>where
>
> countedFrames = (3600 * hours + 60 * minutes + seconds) * frameRate + frames 

does not specify a quantisation to the nearest frame rule, but surely one would be expected?

**Comment by nigelmegitt** [comment]
[Meeting 2016-03-16] Group agrees that with the deprecation of the use of offset times for smpte timebase at the end of [§12.3.1](https://w3c.github.io/ttml2/spec/ttml2.html#timing-time-value-expressions) there is no need to go further in defining this corner case.
