### ISSUE TITLE
Clarify semantics of content bpd for inline and line areas

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#163]
Raised initially for TTML1 at [1].

[1] [https://github.com/w3c/ttml1/issues/212](https://github.com/w3c/ttml1/issues/212)

**Comment by skynavga** [comment]
At present, TTML1 (and TTML2) effectively defer to XSL-FO 1.0 regarding the semantics of inline geometries. As there is no concrete specification of the problem or what clarification may be needed, I am closing this as works for me. If someone wishes to post a PR on this issue, then please reopen.

**Comment by nigelmegitt** [comment]
The use case that this issue was there to try to solve was to allow document authors to specify that the background areas of adjacent lines should meet. Since it is impossible to calculate a `tts:padding` value that extends the area in which the background is painted on a span, because the content size in the block progression direction is unknown, this issue was raised to define the content size in the block progression direction.

If another mechanism is available to achieve the same presentation effect then I am content to leave this closed. However, does this issue not need to be resolved in order to resolve #101?

**Comment by skynavga** [comment]
If anything, this is subsumed by #150. I prefer leaving this closed as either works for me or a duplicate of #150.

**Comment by skynavga** [comment]
The first part of the necessary support was added in #297, where we redefined the semantics of bpd/ipd. The second part is still TBD for #150, which is adding one or more new keywords that can apply to bpd when applied to an inline (span). So, as far as I can tell, this issue (#163) is redundant at this point.
