### ISSUE TITLE
Default play rate

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#164]
In N.2 appears:

<pre>
playRate ∈ ℜ, −∞ < playRate < ∞, playRate is unit-less, and where the value of
playRate is determined by the document processing context;
</pre>

This should be enhanced by adding:

<pre>
, or the value 1.0 if so determined
<pre>

**Comment by nigelmegitt** [comment]
I don't understand how that would be an enhancement. If this is trying to specify a default in case there's no other way to determine it, shouldn't the wording be "... if **not** so determined"? But since it is unit-less, I'm not sure this is even applicable. We simply cannot know or define a default playRate can we?

**Comment by skynavga** [comment]
Yes, it should have said ``if not so determined``. Thanks.

**Comment by nigelmegitt** [comment]
Even so, I don't agree with this. Looking at it again, I think the section is incorrect in multiple ways:

1. Philosophically, playRate must be determined externally and assigning a default is out of scope of the TTML spec and system.
2. The equation assumes a constant playRate; if under some external control the playback is paused, sped up, slowed down, reversed etc then this no longer holds true. I think it would be more correct to integrate the (variable) playRate over time since the real world epoch start time and multiply that integral value by M, to address this, with the additional constraint that no content can be defined for presentation before time zero on the document timeline.
3. The equation and text assumes that the origin for time coordinates is identical to the root temporal extent. I think we can and should separate those two concepts to match the diagram in §12.4.1, and (my interpretation of) the term definition for "Root temporal extent".

**Comment by nigelmegitt** [comment]
Thinking about this a bit more, and what "root temporal extent" should or might mean, following my point 3 above:

If we want the term prefix "root" in general to mean the basis of the coordinate system, as it is used for root container region, then we could perhaps usefully add an additional term prefix "document" to form "document temporal extent" which would be the period between the earliest computed begin time and the latest computed end time (which could be undefined); then a further term "active document temporal extent" or "constrained document temporal extent" would be the intersection between the document temporal extent and any externally defined document activation/deactivation times.

So for example:

```xml
<tt ttp:timeBase="media" ...>
...
<body begin="11m" end="13m">
...
</body>
</tt>
```

In a context that activates this document from 10m until 12m would yield:

* Root temporal extent = 0 --> undefined
* Document temporal extent = 11m -->13m
* [active|constrained] document temporal extent = 11m --> 12m

My understanding of the current definition of "Root temporal extent" is coincident with the third of these right now. I don't see any utility in defining root temporal extent as the zero based coordinate system, since that's unchanging in all cases. It could be useful to define a document temporal extent though, which would apply before any external processing context has stepped in.

This discussion may appear unrelated to the original issue, which is about playRate, but I think it a common basis for understanding is needed in order to resolve that question, and now is as good a time as any to check we have that.

**Comment by skynavga** [comment]
On Wed, Jul 13, 2016 at 6:49 AM, Nigel Megitt <notifications@github.com>
wrote:

> Thinking about this a bit more, and what "root temporal extent" should or
> might mean, following my point 3 above:
>
> If we want the term prefix "root" in general to mean the basis of the
> coordinate system, as it is used for root container region, then we could
> perhaps usefully add an additional term prefix "document" to form "document
> temporal extent" which would be the period between the earliest computed
> begin time and the latest computed end time (which could be undefined);
> then a further term "active document temporal extent" or "constrained
> document temporal extent" would be the intersection between the document
> temporal extent and any externally defined document activation/deactivation
> times.
>
> So for example:
>
> <tt ttp:timeBase="media" ...>
> ...
> <body begin="11m" end="13m">
> ...
> </body>
> </tt>
>
> In a context that activates this document from 10m until 12m would yield:
>
>    - Root temporal extent = 0 --> undefined
>    - Document temporal extent = 11m -->13m
>    - [active|constrained] document temporal extent = 11m --> 12m
>
> My understanding of the current definition of "Root temporal extent" is
> coincident with the third of these right now.
>
I need to check my notes, but I'm pretty sure my understanding of "root
temporal extent" is the first of these. Of at least I think that is what I
intended in using the term. Again, I need to check my notes.
