### ISSUE TITLE
tts:extent="auto" vs tts:extent="100% 100%"

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#215]
Is there any difference between specifying tts:extent="auto" and tts:extent="100% 100%" on a region other than the root container region?

If not, suggest rephrasing:

`If applied to a region other than the root container region and the value of this attribute is auto, then the computed value of the style property must be considered to be the same as the extent of the root container region.`

to

`If applied to a region other than the root container region and the value of this attribute is auto, then the specified value of the style property must be considered to be "100% 100%".`

**Comment by nigelmegitt** [comment]
I think it is generally more useful to have the spec define the _computed_ value than to require extra dereferencing on the part of the reader by defining an alternate _specified_ value as a proxy.

**Comment by skynavga** [comment]
> If not, suggest rephrasing:

I'm in the process of rewriting this text anyway, as part of adding a new appendix on root container region semantics, so I will take your suggestion into consideration.

> I think it is generally more useful to have the spec define the computed value than to require extra dereferencing on the part of the reader by defining an alternate specified value as a proxy.

Actually, that (using a proxy) is the standard way of defining the treatment of auto elsewhere in our spec (and others).

**Comment by skynavga** [comment]
Closing this issue as works for me since:

1. the proposed change does not result in any semantic or behavioral change;
2. the proposed change is inconsistent with the many other cases of using a proxy value for defining equivalence behavior, which allows for better abstraction levels in the specification.

**Comment by nigelmegitt** [comment]
Just reviewing this issue closure: it appears that the original wording from when the issue was opened no longer exists in the current ED. However, the current wording states that `"auto"` is treated as `"auto auto"`, and then under `<measure>`, `"auto"` here is treated as `"available"` which clearly specifies a size less the containing element's border and padding; however numerical measures do not describe if they are before or after subtracting padding and border. This was w3c/ttml1#221 which was resolved in TTML2 by commit 21f4b3fedc1bd63dc69703d2c2e765a50b59a1dc 

Now that commit includes the addition of the text:

> If padding is applied to a region, then the region's extent includes that padding, i.e., padding is applied as an inset, and, therefore, is interior to the region's extent.

and:

> Padding is applied as an inset to a region area, which is to say, the content rectangle of a region area is reduced by the presence of padding applied to the region.

These things are clearly different: `"auto auto"` ends up specifying the largest available content size that _excludes_ padding and border, whereas `"100% 100%"` specifies a content size that _includes_ them. So to return to the original question, right now they are _not_ equivalent. The question now is: is that the semantic that we want?

I am not saying that this does not work for me, but the proposed change would actually result in a semantic or behavioural change. @palemieux what do you think, as the issue raiser? Is this a change you would still advocate?

Also @skynavga was it your intention to specify different size behaviours with respect to padding and borders depending on whether a keyword or a numerical value is used to specify the region extent?

**Comment by skynavga** [comment]
There is no question on intent: extent on region corresponds to border rectangle, which includes padding rectangle, which includes content rectangle. If that's not what the words say, we need to fix it.

**Comment by nigelmegitt** [comment]
@skynavga You do have an editorial note to address ambiguity between "content region" and "region" that could be applicable here.

From [`tts:extent`](https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-extent):

> Values:	`auto | contain | cover | <measure> <measure>`

> If a tts:extent attribute is specified on a region element, then its computed value determines the width and height of the associated content region.

...

> If the value of this attribute is auto, then the computed value of its associated property is determined as follows:
>
> 1. if the property applies to the tt element, then auto is interpreted as if the value contain were specified;
> 2. if the property applies to a region element, either directly or indirectly, then auto is interpreted as if the value "auto auto" were specified;

Then in [`<measure>`](https://w3c.github.io/ttml2/spec/ttml2.html#style-value-measure):

> **auto**
> For ipd, either (1) the intrinsic size in the inline progression direction when applied to an image, or (2) the numeric value that would be obtained if the available value were specified. For bpd, either (1) the intrinsic size in the block progression direction when applied to an image, or (2) the numeric value that would be obtained if the available value were specified.

> **available**
For ipd, the numeric value equal to the ipd of the parent containing block's ipd less the current element's combined border and padding ipd. For bpd, the numeric value equal to the bpd of the parent containing block's bpd less the current element's combined border and padding bpd.

So two things:

1. some of the allowed values are listed explicitly under `tts:extent` and _also_ defined under `<measure>` - if they are supposed to have different meanings then that needs to be made clear; conversely if not then perhaps we can remove the keywords from `tts:extent`?

2. The definition of `available` excludes the border and padding, so those seem to be the words that need fixing.
