### ISSUE TITLE
writingMode and direction interaction

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#221]
Style inheritance propagates `direction="ltr"` (the initial value) on all elements (unless explicitly specified as "rtl" somewhere), thereby overriding any right-to-left direction specified using `writingMode` on region, since, as specified in Section 7.29.1 of XSL, `direction` takes precedence over `writingMode`.

As specified in Section 7.29.1 of XSL, the TTML style resolution process needs to specify that, whenever specified, `writingMode` also sets the value of `direction` to the horizontal direction implied by `writingMode`.

See also https://lists.w3.org/Archives/Public/public-tt/2016Nov/0027.html

**Comment by skynavga** [comment]
@palemieux the first paragraph in the initial comment above is not quite correct: in particular, the language in XSL-FO 7.29.1 states:

>This direction may override the inline-progression-direction determined by the current writing-mode and the implicit direction determined by the Unicode BIDI algorithm.

This must be interpreted in the context of the use of direction in combination with the unicode-bidi property (in XSL-FO/CSS) with inline elements. In this case, the following original language from CSS (also cited by XSL-FO) applies:

>For the 'direction' property to have any effect on inline-level elements, the 'unicode-bidi' property's value must be 'embed' or 'override'.

So I think no action is required regarding your first comment.

Regarding your second comment above, I think you are referring to the following language in XSL-FO 7.29.1:

>To insure consistency with the "writing-mode" property, the "direction" property is initialized to the value that sets the same inline-progression-direction as is set by the "writing-mode" property whenever that "writing-mode" property sets that direction. If the "direction" property is explicitly specified on the same formatting object the value of the "direction" property will override the inline-progression-direction set by the "writing-mode".

In this regard, I agree that we need additional language that ensures consistency with this requirement. In particular, since tts:writingMode applies only to region, we need a little bit of extra language that states that the if tts:writingMode is specified on region, then the computed value of tts:direction on that region, if not explicitly specified, is set to the direction implied by the computed value of tts:writingMode on that region. Would you agree?

I will go ahead and post a PR to this effect.

**Comment by palemieux** [comment]
> since tts:writingMode applies only to region

Yes, `tts:writingMode` applies only to region but is _inherited_ down to inline elements, so, on a given element, `tts:direction` should override `tts:writingMode` only if `tts:direction` is specified.

**Comment by skynavga** [comment]
On Fri, May 26, 2017 at 1:15 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> since tts:writingMode applies only to region
>
> Yes, tts:writingMode applies only to region but is *inherited* down to
> inline elements, so, on a given element, tts:direction should override
> tts:writingMode only if tts:direction is specified.
>
tts:writingMode is not an inherited property, even though its semantic
effects (having been applied to a region) dictate the applicable block and
inline progression directions of content elements assigned to that region;
just think of direction this way:

   - on a p, it sets the default embedding level for that p
   - on a span it supplies a parameter to the interpretation of
   tts:unicodeBidi

since direction is inherited, then any element between region and the p or
span may specify a value (which propagates downward); otherwise, the
computed value from region is what gets inherited

**Comment by palemieux** [comment]
> tts:writingMode is not an inherited property,

Right! So yes, _if tts:writingMode is specified on region, then the computed value of tts:direction on that region, if not explicitly specified, is set to the direction implied by the computed value of tts:writingMode on that region_.

**Comment by palemieux** [comment]
... although even though `tts:writingMode` is not inherited, it can be specified anywhere, so the text probably needs to say: _if tts:writingMode is specified on an element, then the computed value of tts:direction on that element, if not explicitly specified, is set to the direction implied by the computed value of tts:writingMode on that region_

**Comment by skynavga** [comment]
On Fri, May 26, 2017 at 1:45 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> tts:writingMode is not an inherited property,
>
> Right! So yes, *if tts:writingMode is specified on region, then the
> computed value of tts:direction on that region, if not explicitly
> specified, is set to the direction implied by the computed value of
> tts:writingMode on that region*.
>
> Have you looked at the new language here [1]? Is there a technical problem
you are suggesting with this language?

[1]
https://github.com/w3c/ttml2/pull/338/files#diff-5ac39ab39265717d36dfd789d254ce1aR8837

**Comment by skynavga** [comment]
On Fri, May 26, 2017 at 1:50 PM, Pierre-Anthony Lemieux <
notifications@github.com> wrote:

> ... although even though tts:writingMode is not inherited, it can be
> specified anywhere, so the text probably needs to say: *if
> tts:writingMode is specified on an element, then the computed value of
> tts:direction on that element, if not explicitly specified, is set to the
> direction implied by the computed value of tts:writingMode on that region*
>
> That would not be the case. A non-inherited property on an element to
which it does not apply is completely ignored.

**Comment by palemieux** [comment]
> That would not be the case. A non-inherited property on an element to which it does not apply is completely ignored.

Where does it say that? I am curious.
