### ISSUE TITLE
Incomplete support for IMSC1 line padding.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#237]
To the extent that IMSC2 is intended to be subset of TTML2, TTML2 needs to support `http://www.w3.org/ns/ttml/profile/imsc1/extension/#linePadding`.

While TTML2 adds support for padding on `span`, it is not equivalent to `#linePadding`. Specifically, `#linePadding` requires that the background of the first/last character of each line
be extended, regardless of whether the line was wrapped explicitly using `br`.

In contrast, `padding`, in the CSS/XSL sense, adds padding to the edges of the `span` regardless of whether the edge is actually on the start or end of a line. This means that additional gaps and color mismatch will be introduced if nested spans are used, even if `box-decoration-break: clone` is used.

See examples at https://codepen.io/palemieux/pen/vyzbqW.

**Comment by skynavga** [comment]
Could you add an image showing what IMSC1 line padding expects as a rendering given the examples in your codepen?

**Comment by palemieux** [comment]
Bottom `p` at https://codepen.io/palemieux/pen/bgovKB is the expected result. The top `p` is as currently specified using padding on `span`.

**Comment by skynavga** [comment]
@palemieux just want to confirm that the bottom codepen example is as it should appear, i.e., with both a green and red padding at end of bottom line?

**Comment by skynavga** [comment]
I am presently considering a solution that involves introducing a ``tts:boxDecorationBreak`` attribute with values ``{slice,clone,cloneMostNested}``, where ``cloneMostNested`` is the default initial value (rather than ``clone``). To make implementations easier, I would require that the default initial value semantics be required to support a new #padding-inline designator that features padding on inlines. However, full support for all three values would only be required by a new #boxDecorationBreak feature. I am planning to post a new PR to this effect sometime today.

I have sent email to fanatsai and Rossen (in CSSWG) asking for their feedback on this idea.

**Comment by skynavga** [comment]
Ended up using ``tts:inlineAreaBreak`` for consistency with existing TTML terminology based on XSL-FO areas rather than CSS boxes.

**Comment by nigelmegitt** [comment]
Thanks @skynavga this makes sense to me. On the codepen I see no red on it at all, so not sure about your question, but yes, the bottom example is correct, i.e. the most nested (green) background is cloned but not the black background of the less nested ancestor element.

**Comment by skynavga** [comment]
It appears that @palemieux has updated the codepen examples, as there was previously a cloned red padding that appeared at the end of the second line of the third example (now merged into the second example).
