### ISSUE TITLE
rubyAlign and wide ruby text 

### ISSUE THREAD

**Issue by r12a** [w3c/ttml2#250]
10.2.34 tts:rubyAlign
https://www.w3.org/TR/2016/WD-ttml2-20161117/#style-attribute-rubyAlign

> The tts:rubyAlign attribute is used to specify the position of ruby text within the inline area generated by the ruby text container annotation.

What about the (common) case where the ruby text is longer than the base text?  Note that in CSS a property such as ruby-align applies the distribution of text to the smaller of the ruby text _or_ base text, rather than just to the ruby text, ie. it operates on the shorter of the two.

**Comment by dae-kim** [comment]
In the case of "auto": otherwise (NR is greater than NB), the semantics of center apply

Are you asking we add this info within the intro sentence?

**Comment by r12a** [comment]
I'm saying that it seems to me that the whole section ignores the case where the ruby annotation is wider than the base characters (in terms of space, not NR vs NB). Thus `tts:rubyAlign` set to `spaceAround` would do what one expects with the example on the left below (where annotation is shorter than the base), ie. it would space the annotation out over the longer base; but the spec doesn't specify what would happen in the case of the example on the right (where the base is shorter than the annotation). My expectation, and that of CSS, would be that the `spaceAround` algorithm would be applied to the **base** characters, rather than to the annotation.

![ruby-align-around](https://cloud.githubusercontent.com/assets/4839211/25916955/5d93b23e-35be-11e7-8c2e-da40106588f9.png)

I think this applies to all the values of rubyAlign.

Is that clearer?

**Comment by dae-kim** [comment]
In this case, TTML2 should require that rubyAlign shall be "center".

In a subtitle context, we generally want to avoid altering base characters in any way for the sake of ruby.
Japanese subtitle authors severely limit the use of rubies to work around base characters. They do not insert whitespace -- they omit ruby altogether. This is similar to sacrificing subtitle accuracy to dialogue for the sake of time and screen space constraints.

Even in the case of rubyOverflow and rubyOverhang, I very highly doubt any values that affect base characters will be used. These were necessary evils for the sake of completion IMO, but far more simple to implement than applying algorithms to base rather than annotation.

If push comes to shove, it would be far more practical to edit down rubyOverflow and rubyOverhang than expand on rubyAlign (though I am not opposed to revisiting this in ttml.next).

This brings up a need to revisit Ruby Module and JLReq to address differences when considering a subtitle context and incorporating rubyReserve, rubyOverhangClass, etc.

**Comment by r12a** [comment]
So, take the TTML equivalent markup to the following (i'm using html markup because it's easier and because it will display here).

これは<ruby><rb>昔</rb><rt>むかし</rt><rb>話</rb><rt>ばなし</rt></ruby>です。

ie. `これは<ruby><rb>昔</rb><rt>むかし</rt><rb>話</rb><rt>ばなし</rt></ruby>です。`

By default, `rubyOverhang` is set to allow, and `rubyOverHangClass` allows overlap of the surrounding characters, but presumably overlap cannot occur between the two bases(?). What happens?

And what happens if you have the following at the start of a line with rubyOverflow set to default:
<ruby><rb>昔話</rb><rt>むかしばなし</rt></ruby>fairy storyです。
ie. `<ruby><rb>昔話</rb><rt>むかしばなし</rt></ruby>fairy storyです。`
given that by default it is expected that the ruby annotation won't overhang Latin text in Japanese?

I don't see how you can get around those issues without opening up small gaps around the base characters, or really botching the associations between base and annotations. 

Please take the examples above and show me what you'd expect to see in TTML.

**Comment by dae-kim** [comment]
In your first example, the TTML rendering will mimic the display in your comment.
But that is not how a subtitle author would format that text. A subtitle author would group the annotations and base together:

`これは<ruby><rb>昔話</rb><rt>むかしばなし</rt></ruby>です。`

They would also explicitly set rubyOverhang to "overlap" or "always":

![ruby001](https://cloud.githubusercontent.com/assets/15376166/25971846/9755fa42-3652-11e7-9b65-b8284b7d9cff.PNG)

The same changes would be applied to your second example + explicitly set rubyOverflow to "overflow":

![ruby002](https://cloud.githubusercontent.com/assets/15376166/25971943/e3b59f32-3652-11e7-8a5a-e10fc239e61c.PNG)

If we were to preserve your settings, then yes, the render would look "botched".

**Comment by r12a** [comment]
> If we were to preserve your settings

But these are the default settings for TTML, so shouldn't the defaults be changed then?, to avoid the content authors have to constantly make explicit changes (and by the look of it, for individual ruby instances). I believe it's common for phonetic annotations to be longer than the base text.

The solution you describe for the first example handles the annotation as if it were group ruby. This means that, when 昔話 hits the end of a line, the whole word will wrap, rather than just the second character and its annotation. That's not normally how ruby works. 

There also seems to be an issue as the number of character in the base sequence grows.

What happens when you try to annotate Chinese text?  Let's as an example suppose that we want to annotate the pronunciation in pinyin for part of the UDHR.

鉴于对人类家庭所有成员的固有尊严及其平等的和不移的权利的承认,乃是世界自由、正义与和平的基础,

the pinyin would be as follows:

Jiànyú duì rénlèi jiātíng suǒyǒu chéngyuán de gùyǒu zūnyán jí qí píngděng de hé bù yí de quánlì de chéngrèn, nǎi shì shìjiè zìyóu, zhèngyì yǔ hépíng de jīchǔ,

Even if the subtitle in practice applied the ruby to just a part of this at a time, you run into a couple of problems. Because many of the annotations are longer than the base text they annotate, and because there is no kana, you can't soak up the overhanging annotations by overlapping - you'd _have_ to push the base characters apart slightly to accomodate multiple annotations if you want to associate the phonetics with specific base characters (which is the norm). If, however, you ignore the associations and try to pack the annotations into a long string (as you did for the japanese example above), you can end up with long annotations that would not break at line ends, and would probably overflow line ends significantly, and which would no longer show the correspondence of sounds to individual base characters.

How would you expect chinese like this to be handled?

**Comment by dae-kim** [comment]
> That's not normally how ruby works.

The problem here is, your definition of "normal" comes from a CSS/JLReq point of view.
While we do our best to incorporate guidelines from CSS/JLReq, it is clear subtitles were never considered.

This disconnect is highlighted by your pinyin case. A subtitle would never be able to fit that much base text into one subtitle event. So that string of text would have to be broken into multiple events. Once broken into multiple events, it is much easier to deal with longer annotations. At worst, they can set rubyOverhang to "always".

But let me reiterate that the Japanese subtitler works from an assumption that rubyOverhang is always set to "overlap". This is one of the restrictions Japanese subtitlers have always worked around.

This isn't just limited to the Japanese subtitler. We have to be mindful of the limitations all subtitlers work around. For plain English Closed Captions, a closed captioner cannot fit "Supercalifragilisticexpialidocious!" into one line. They have to intentionally misspell the word or break that word artificially. Even for more lenient standards like SDH, an English subtitler cannot fit "Taumatawhakatangi­hangakoauauotamatea­turipukakapikimaunga­horonukupokaiwhen­uakitanatahu" into one event -- let alone one line. 

The only actionable item from this issue seems to be "change the default values of some ruby attributes".

And maybe we should revisit JLReq: "The main target of this document is common books ... the importance of magazines, technical manuals, and Web documents rates alongside common books. However, there are several characteristics in these publications, which are different from common books. These issues should be treated more fully in future documents."

Perhaps this is a good opportunity to start drafting a future document that focuses on subtitles/SDH/Closed Captions/Teletext?

**Comment by dae-kim** [comment]
@skynavga @r12a
Since "spaceBetween" and "spaceAround" deal specifically with excess whitespace, perhaps we can add: if there is no excess whitespace, semantics of "center" apply.

**Comment by r12a** [comment]
That's a clear and useful note. Thanks.  I'll suggest to the i18n WG that we close our tracker on this.

**Comment by cconcolato** [comment]
Can you approve the PR?

**Comment by skynavga** [comment]
@r12a @cconcolato as a reminder, the intention of ``tts:rubyOverhang``, as shown in the last TTML2 WD [1], was to deal with the case of ruby text ipd exceeding ruby base text ipd. The initial value of ``tts:rubyOverhang`` was defined as ``allow``, which allowed overhang of the ruby text with the adjacent base text. In contrast, the value ``none`` caused the insertion of filler space at the start and end edges of the inline area generated by the base text. An alternative approach to achieving non-overlap, which was not mentioned,  would have been the insertion of filler space between base glyph areas, resulting in a space between or space around alignment of the base glyph areas with respect to the ruby text glyph areas. So the comment [2] is not quite accurate, since it did indeed treat this case (of wider ruby text).

At this point in time, we have removed ``tts:rubyOverhang``, including the language that governed the default (initial value) case ``allow``. So, what we are left with is implementation dependent behavior in the case of wider ruby text. Part of our agreement to remove ``tts:rubyOverhang`` was that we would leave these semantics as undefined (and therefore, implementation dependent) in TTML2. Consequently, I think we do not need to specify the possible implementation strategies in TTML2.

The proposed note is very close to adequate, however, we need to change "distributed in the base text" to merely "distributed" in order to avoid giving the wrong impression that distributing space in the base text is the only option. I will update the PR #605 to effect this change.

[1] https://www.w3.org/TR/ttml2/#style-attribute-rubyOverhang
[2] https://github.com/w3c/ttml2/issues/250#issuecomment-300586931

**Comment by r12a** [comment]
The i18n WG agreed to close our tracker for this issue.
