### ISSUE TITLE
Metadata examples do not include xml:lang (editorial) 

### ISSUE THREAD

**Issue by aphillips** [w3c/ttml2#271]
https://w3c.github.io/ttml2/spec/ttml2.html#metadata-vocabulary-metadata

There are several examples of `ttm:title` or `ttm:desc` containing natural language text, but no `lang` attributes are supplied.

**Comment by palemieux** [comment]
@aphillips Proposed resolution at https://github.com/w3c/ttml2/issues/301. Please review.

**Comment by palemieux** [comment]
@skynavga I see that the PR changed significantly from #301. Please confirm with @aphillips that he is ok with the disposition.

**Comment by skynavga** [comment]
PR #307 merged. No outstanding substantive comments, so closing.

**Comment by aphillips** [comment]
PR#307 appears to address a different issue. This editorial comment was about the quoted section, which introduces the `metadata` element and then goes on to show several examples that contain natural language text (_Chapter 6 – Sherlock Holmes Gives a Demonstration_) without the use of `xml:lang`. 

While cluttering up all of your examples with all of the possible metadata values is not helpful to readers, at the same time the I18N WG encourages the use of language and direction metadata and we generally *do* request that specs illustrate best practices where it is not intrusive to the example to do so. Since the examples here are meant to show metadata being used, it would be a Good Idea to include `xml:lang` in at least on of them.

**Comment by skynavga** [comment]
Actually, no. #307 addresses the cited issue, and does so in the correct location, namely, under the section on xml:lang. There is no need to clutter the examples of metadata in section 14 by introducing xml:lang usage in that context. I expect the WG will conclude this matter at the upcoming telecon on Thursday, which you are welcome to join.

**Comment by nigelmegitt** [comment]
@aphillips does https://github.com/w3c/ttml2/issues/271#issuecomment-301934366 make sense to you?

Reopening and moving to group milestone.

**Comment by aphillips** [comment]
@nigelmegitt It does and it doesn't. It does from the point of view that I agree with the current text, etc. in the section on `xml:lang`. It doesn't from the point of view that I18N prefers to see examples showing `xml:lang`. Further the section on `xml:lang` illustrates the use of that attribute when there are multiple languages preset. However, language metadata is generally necessary even when no localization is taking place and there is only a single language in the document.

So I stand by the original request in this issue: show or illustrate best practices by including `xml:lang="en"` on at least one of the examples. I'm not looking for text or notes saying "hey look at the `xml:lang` attributes", just inclusion in the example(s) because people pattern after what they see in specifications.

If your working group does not agree, that's fine. But honestly, this is a complaint I get all the time (in other spec discussions about document formats as well as in my day job). My rejoinder is: language metadata is not clutter. It is necessary to the proper functioning of the Web.

**Comment by nigelmegitt** [comment]
Thanks @aphillips in that case I will propose a pull request to add such an example in §1.2 Document Example rather than "cluttering" other examples in the spec.

**Comment by skynavga** [comment]
There is no need to add one to the example in §1.2, we now have one in the example under §8.2.8. What would it add that is not already covered under §8.2.8? We most certainly are not going to add xml:lang to every example that uses metadata, even when it is a natural language value.

**Comment by nigelmegitt** [comment]
@skynavga my proposal will address https://github.com/w3c/ttml2/issues/271#issuecomment-302747180 by including `xml:lang="en"` on _at least one_ of the examples. Nobody is proposing adding `xml:lang` to every example.

**Comment by r12a** [comment]
This is related, and is part question, part tentative suggestion.

The `tt` element has to have an `xml:lang` attribute (which is great). But in examples where there is text in more than one language, I have a question.

If TTML is displayed in a browser, and if a font isn't explicitly specified (or the font specified doesn't have glyphs for the characters displayed), will the browser pick a font itself, like it does for HTML?

The issue here is that, for example, some browsers apply chinese fonts by default to ideographic characters, whereas others apply japanese fonts, unless the language is specified - and that can be a problem, because you don't want to present chinese users with text that looks like japanese, and vice versa.

And here's the tentative suggestion:

I spotted two examples containing multiple scripts:
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction and
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-writingMode

In the latter, no font is specified in the style declarations and no language tag is set.  Might that be an example where we should use the language tag/and or assign a font? Should we add a language to `span` in the other example too?

(For info, note btw that browsers tend to apply different fonts for `ar` and `fa` labelled text, in a similar way to the ideographic example it gave above.)

**Comment by skynavga** [comment]
On Wed, May 24, 2017 at 10:40 AM, r12a <notifications@github.com> wrote:

> This is related, and is part question, part tentative suggestion.
>
> The tt element has to have an xml:lang attribute (which is great). But in
> examples where there is text in more than one language, I have a question.
>
> If TTML is displayed in a browser, and if a font isn't explicitly
> specified (or the font specified doesn't have glyphs for the characters
> displayed), will the browser pick a font itself, like it does for HTML?
>
I guess you mean with the TTML presentation processor pick a font itself.
The answer lies in a TBD portion of the TTML2 spec [1], which I intend to
fill out based on language in XSL-FO, CSS2, and CSS3 Fonts.

[1]
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-fontSelectionStrategy

As for TTML1, all one can say is that it is not specified, so it
effectively delegates to XSL-FO semantics, which is in some cases tied to
CSS2 semantics. As a result, there is a certain amount of unspecified
implementation dependent behavior in this regard. I'm hoping we can do a
better job of nailing this down (to some extent) in TTML2.

> The issue here is that, for example, some browsers apply chinese fonts by
> default to ideographic characters, whereas others apply japanese fonts,
> unless the language is specified - and that can be a problem, because you
> don't want to present chinese users with text that looks like japanese, and
> vice versa.
>
Since we don't (yet) specify behavior in this area, other than by
delegating to XSL-FO, it is entirely possible that an implementation may:

   - ignore xml:lang for character to glyph mapping, using script only (as
   a fixed character property)
   - use xml:lang for character to glyph mapping along with script
   - use text analysis heuristics to guess language, possibly using
   xml:lang information or not, along with script

SKYNAV (and XFSI before it) has implemented both the first and second of
these approaches. We have never been tasked to go as far as text analysis.

> And here's the tentative suggestion:
>
> I spotted two examples containing multiple scripts:
> https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-direction and
> https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-writingMode
>
> In the latter, no font is specified in the style declarations and no
> language tag is set. Might that be an example where we should use the
> language tag/and or assign a font? Should we add a language to span in
> the other example too?
>
Given that in both of these contexts, multiple natural languages appear in
examples, I would have no objection to adding language tags here (as well
as additional notes if useful).

**Comment by aphillips** [comment]
If an implementation uses only script for font fallback selection, the results will be disappointing for shared script text---notably the CCJK languages. For these, having language metadata is the best way of getting predictable results.

Although I've written some text analysis engines over the years, generally they operate on a different level (providing the language tag when it is not available on the content, such as when Kindle displays a text file). Generally when rendering text, performance is too key a consideration (and there may not be enough data) to do text analysis on the fly.

**Comment by skynavga** [comment]
On Wed, May 24, 2017 at 12:09 PM, Addison Phillips <notifications@github.com
> wrote:

> If an implementation uses only script for font fallback selection, the
> results will be disappointing for shared script text---notably the CCJK
> languages. For these, having language metadata is the best way of getting
> predictable results.
>
Agreed. But it may still be legible, though users may complain.

> Although I've written some text analysis engines over the years, generally
> they operate on a different level (providing the language tag when it is
> not available on the content, such as when Kindle displays a text file).
> Generally when rendering text, performance is too key a consideration (and
> there may not be enough data) to do text analysis on the fly.
>
It depends on where text analysis is performed. Since browsers tend to not
support TTML rendering directly, it is often the case that TTML is rendered
(into SVG, PNG, etc) on a server prior to delivery. In such contexts, it
may be practical to infer missing language information. For example, in the
writing mode example you cite, the CJK text is written solely in hiragana,
which can readily be associated with xml:lang="ja" even without performing
text based analysis.

My point in raising this is that there is an intermediate option between
full language tagging and no language tagging; nonetheless, as I said
above, I would not object to tagging these text segments.

**Comment by aphillips** [comment]
@skynavga I agree about the "may still be legible". 

I think we're in violent agreement. My concern for the document format standard is that we provide the mechanism and suggest to implementations to pay attention to it.

**Comment by skynavga** [comment]
On Wed, May 24, 2017 at 1:33 PM, Addison Phillips <notifications@github.com>
wrote:

> @skynavga <https://github.com/skynavga> I agree about the "may still be
> legible".
>
> I think we're in violent agreement. My concern for the document format
> standard is that we provide the mechanism and suggest to implementations to
> pay attention to it.
>
OK, but we do define the authorial mechanism, xml:lang, which has been
around since DFXP/TTML1. And to restate the latter part of your comment is
sort of like saying: we define a car so that the gas pedal causes the car
to go; implementers are advised to provide a gas pedal.

**Comment by nigelmegitt** [comment]
@skynavga wrote:

> nonetheless, as I said above, I would not object to tagging these text segments.

So let's do that, which appears to resolve the issue to everyone's satisfaction.

**Comment by skynavga** [comment]
Addressed in e4ffcc6ac99b44838d3f33d0c2c0611f80627fe1. @aphillips please state whether this resolves your outstanding comments.

**Comment by skynavga** [comment]
No response from commenter since May 25 request to provide any further comment; therefore, am closing based on the assumption this issue has been resolved by prior mergers.

**Comment by r12a** [comment]
The i18n WG has closed its tracker for this issue.
