### ISSUE TITLE
Clarify/summarize use of foreign namespace elements and attributes.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#387]
Since this topic was such a lengthy discussion recently in TTML1 and IMSC, I recommend adding the same final informative summary text that was added to IMSC that can be found in w3c/imsc/issues/213 and the related PR. Perhaps add it to section 4.1 with a forward reference to 14.1.1 where there are examples.

**Comment by nigelmegitt** [comment]
That'd work for me, perhaps in a note, since it is informative.

**Comment by skynavga** [comment]
Actually, the changes introduced in https://github.com/w3c/imsc/pull/216/files are, at minimum, a mischaracterization of TTML1, and possibly just wrong. In particular, the language introduced there fails to distinguish between foreign vocabulary that may appear in a concrete representation of a TTML document instance (i.e., as an XML document) versus foreign vocabulary that may appear in a TTML abstract document instance. In the former, any foreign vocabulary may appear anywhere. However, in the latter, no foreign vocabulary appears anywhere, since it has been pruned. For purposes of validity assessment according to Section 4.1, no foreign vocabulary will be encountered.

So, we can't just take the text that has been erroneously introduced in IMSC and shoe-horn it into TTML2, at least, not without considerable rewriting.

**Comment by nigelmegitt** [comment]
That language is not necessarily wrong in the context of IMSC @skynavga  since IMSC specifies what is permitted in a (serialised) concrete document instance.

**Comment by skynavga** [comment]
ok; but we can't make reference to that language from TTML2 (as suggested above by @mikedo) since it is not accurate for TTML[12]

**Comment by skynavga** [comment]
This will be addressed by implementation of https://github.com/w3c/ttml2/issues/439#issuecomment-356439840.
