### ISSUE TITLE
Change styling to use CSS.

### ISSUE THREAD

**Issue by tmichel07** [w3c/ttml2#444]
Comment sent byDavid Singer <singer@apple.com>
Date: Sat, 30 Sep 2017 17:49:32 -0700
https://lists.w3.org/Archives/Public/public-tt/2017Oct/0001.html

The styling model used in TTML2 is not CSS and is not processable by a processor/rendering-engine designed to support HTML/CSS.  This leads to complex ‘come from’ process deep in rendering engines, where the behavior has to be dependent on whether the text ‘came from’ an HTML/CSS context or a TTML context.

Please consider adopting CSS as-is, without embellishment or improvement.

David Singer
Manager, Software Standards, Apple Inc.

**Comment by tmichel07** [comment]
Discussion started on the public-tt@w3.org list
https://lists.w3.org/Archives/Public/public-tt/2017Oct/

**Comment by skynavga** [comment]
According to prior WG decisions, we have adopted in TTML style vocabulary based on XSL-FO and CSS. In doing so, we have made minor editorial changes to conform to the TTML camel case name convention, and, have, on occasion, added new keywords or value syntax as extensions. The WG has an active liaison with the CSS WG and is at present discussing a number of requirements as well as possible solutions that can be adopted; however, in the absence of solutions to requirements, new functionality has been defined in TTML as needed and this functionality has been proposed for adoption in CSS. The bottom line is that TTML must satisfy certain functional requirements whether or not they are satisfied by CSS, which is merely one possible vehicle for rendering TTML content.

**Comment by skynavga** [comment]
As there is no practical action that can come from this issue as stated, other than restating the above design philosophy that has and continues to apply to TTML, I am closing this issue as works for me. The WG may wish to discuss at further length if needed.

**Comment by tmichel07** [comment]
Glenn,

I don't think this type of issue should be closed without at least 
responding to the commenter and try to collect his approval.

thierry

Le 03/10/2017 à 20:39, Glenn Adams a écrit :

**Comment by dwsinger** [comment]
There is much practical action that can and should come from this. Look at the CSS compatibility at <https://www.w3.org/wiki/TTML/CSSRequirements> and weep, then start making changes to TTML to match what CSS does, instead of trying to 'improve', and work with the CSS group to get the features needed either for captions or better handling of styling in general, introduced into CSS.

**Comment by skynavga** [comment]
So, we can't (or won't) change any of the following:
- style property naming convention
- existing TTML1 style property names or values

That limits any changes to new TTML2 style properties. Except for changes to align naming convention and semantic consistency, we have adopted XSL-FO or CSS keywords or value syntax for new properties. And, when insufficient functionality existed in CSS, we had to forge ahead, but have started a dialog with the CSS WG.

Rather than making blanket proposals about adopting CSS as is, I want to see case-by-case proposals that would arguably improve compatibility within the confines of the existing constraints and practice.

**Comment by nigelmegitt** [comment]
> start making changes to TTML to match what CSS does, instead of trying to 'improve', and work with the CSS group to get the features needed either for captions or better handling of styling in general, introduced into CSS.

See #406 - I'm in progress doing the editing work for that to align with CSS semantics.

We are already working with the CSS group to get features needed added to CSS. When the WG has discussed the options and impacts of waiting for CSS to include the necessary features, there has been a clear consensus _not_ to wait.

**Comment by dwsinger** [comment]
re: "Rather than making blanket proposals about adopting CSS as is, I want to see case-by-case proposals that would arguably improve compatibility within the confines of the existing constraints and practice."

I think this reveals a major misconception that many of us have had for many years (including me): that captioning support is typically supplied by a native implementation that reads 'static' input files directly. Actually, in browsers at least, this is often far from the case; captioning is supported by polyfills etc. that translate the incoming format into HTML/CSS. When the semantics of the input cannot be matched in HTML/CSS, this becomes a nightmare. So the answer to the question is: every line that's not green in the https://www.w3.org/wiki/TTML/CSSRequirements  page.

**Comment by skynavga** [comment]
On Wed, Oct 4, 2017 at 10:47 AM, David Singer <notifications@github.com>
wrote:

> re: "Rather than making blanket proposals about adopting CSS as is, I want
> to see case-by-case proposals that would arguably improve compatibility
> within the confines of the existing constraints and practice."
>
> I think this reveals a major misconception that many of us have had for
> many years (including me): that captioning support is typically supplied by
> a native implementation that reads 'static' input files directly. Actually,
> in browsers at least, this is often far from the case; captioning is
> supported by polyfills etc. that translate the incoming format into
> HTML/CSS. When the semantics of the input cannot be matched in HTML/CSS,
> this becomes a nightmare. So the answer to the question is: every line
> that's not green in the https://www.w3.org/wiki/TTML/CSSRequirements page.
>
A client based polyfill that translates to HTML/CSS is only one possible
option. Other options include

   - client based polyfill that translates to SVG
   - server based translation to SVG
   - native client rendering support

The use of desktop/mobile browsers is only one domain of deployment. There
are many others as well. Furthermore, if you recall, TTML was originally an
authoring format with multiple possible distribution formats, one of which,
DFXP, eventually became TTML in a concrete representation. As such, the use
and requirements pertaining to authoring have a major role, and in this
role, limitations of particular rendering strategies should not be the
driving force.

**Comment by dwsinger** [comment]
As a distribution/archiving/etc. format this is indeed less problematic, and indeed the initial focus of TTML. Unfortunately it's being increasingly moved as a delivery format in a number of venues, so these questions then become very relevant.

**Comment by nigelmegitt** [comment]
As a disposition, I would propose something like:

> Thank you for your review comment regarding TTML2 styling. Given the background of TTML we will not adopt CSS syntax as-is but continue with a TTML syntax that can in principle be mapped to CSS where that is helpful. We have identified some use cases which are not supported by CSS semantics; moreover it is not a requirement that presentation processors are implemented using CSS. However we agree that eventually it is desirable that all TTML style features can be mapped with fidelity to CSS equivalents, and will continue to work with the CSS WG towards achieving this goal. We would welcome all assistance in reaching this goal, including from browser implementers such as Apple.

**Comment by dwsinger** [comment]
I can accept that this is a goal and a work in process...
