### ISSUE TITLE
Processor backwards compatibility.

### ISSUE THREAD

**Issue by mikedo** [w3c/ttml2#458]
This is a proposal based on the discussion from the 5-Oct WG meeting on this topic. See also: w3c/ttml2#442 and w3c/imsc1#258.

Background: several of us are concerned about backwards compatibility of TTML1/TTML2 presentation processors, especially in the context of IMSCvNEXT. Specifically, the concern is that a conformant IMSC1 document (optionally including TTML2 features such as tts:disparity) creates the same presentation out of an IMSCvNEXT presentation processor as an IMSC1 presentation processor.  And, not because it might be the same author of the implementation.  This potentially could be solved with conformance statements in IMSCvNEXT except to the extent it references TTML2 (rather than TTML1) when TTML2 itself is potentially conflicting (at least for documents it determines to be version=2) and not subject to such a constraint.

Examining TTML2… 

Re section 3.4:

3.4.2 …A conforming TTML2 processor should be able to process a TTML1 content document instance; however, it may emit warnings if it encounters deprecated features.

Why is the above a “should” and not a “shall”?  That is, when would it be permitted/desirable for it to deviate?

There is no specific statement about presentation processor backwards compatibility. The fact that it is also a “processor” is inadequate since TTML2 is generally silent about presentation details across implementations as well as between TTML1 and TTML2, except for an informative note listing example permitted variations across implementations, inferring there are more that go unstated:

3.2.3 "…Note:
Two conforming presentation processors are not required to produce the same presentation when processing the same conforming document. For example, different presentation processors may use different fonts, different font rasterizers, different line break algorithms, as well as different implementations of behavior not prescribed by this specification."

Although this is an accurate general representation of the potential variations between implementations, the silence of the substantive statement that is desirable: “all other things being equal, the presentation shall be deterministic and consistent across implementations”. But this is testable without an exhaustive list of permitted implementation-dependent variations.

Whether we alter the above conformance provisions or not, I think I am leaning to make a broad scope statement about the intent of the TTML2 specification itself of the form: “The provisions of this specification covering TTML1 features are intended to be identical to those same provisions in TTML1. That is, any deviation is unintended.”

**Comment by skynavga** [comment]
On Wed, Oct 11, 2017 at 11:55 AM, Michael A Dolan <notifications@github.com>
wrote:

> This is a proposal based on the discussion from the 5-Oct WG meeting on
> this topic. See also: w3c/ttml2#442
> <https://github.com/w3c/ttml2/issues/442> and w3c/imsc1#258
> <https://github.com/w3c/imsc/issues/258>.
>
> Background: several of us are concerned about backwards compatibility of
> TTML1/TTML2 presentation processors, especially in the context of
> IMSCvNEXT. Specifically, the concern is that a conformant IMSC1 document
> (optionally including TTML2 features such as tts:disparity) creates the
> same presentation out of an IMSCvNEXT presentation processor as an IMSC1
> presentation processor. And, not because it might be the same author of the
> implementation. This potentially could be solved with conformance
> statements in IMSCvNEXT except to the extent it references TTML2 (rather
> than TTML1) when TTML2 itself is potentially conflicting (at least for
> documents it determines to be version=2) and not subject to such a
> constraint.
>
> Examining TTML2…
>
> Re section 3.4:
>
> 3.4.2 …A conforming TTML2 processor should be able to process a TTML1
> content document instance; however, it may emit warnings if it encounters
> deprecated features.
>
> Why is the above a “should” and not a “shall”? That is, when would it be
> permitted/desirable for it to deviate?
>
Two reasons: (1) this section is non-normative; (2) it should be possible
to create a strictly TTML2 only processor (at the choice of the
implementer).

> There is no specific statement about presentation processor backwards
> compatibility. The fact that it is also a “processor” is inadequate since
> TTML2 is generally silent about presentation details across implementations
> as well as between TTML1 and TTML2, except for an informative note listing
> example permitted variations across implementations, inferring there are
> more that go unstated:
>
> 3.2.3 "…Note:
> Two conforming presentation processors are not required to produce the
> same presentation when processing the same conforming document. For
> example, different presentation processors may use different fonts,
> different font rasterizers, different line break algorithms, as well as
> different implementations of behavior not prescribed by this specification."
>
> Although this is an accurate general representation of the potential
> variations between implementations, the silence of the substantive
> statement that is desirable: “all other things being equal, the
> presentation shall be deterministic and consistent across implementations”.
> But this is testable without an exhaustive list of permitted
> implementation-dependent variations.
>
Deterministic rendering is impossible across implementations. This is not
and never has been a requirement for TTML1 or TTML2.

> Whether we alter the above conformance provisions or not, I think I am
> leaning to make a broad scope statement about the intent of the TTML2
> specification itself of the form: “The provisions of this specification
> covering TTML1 features are intended to be identical to those same
> provisions in TTML1. That is, any deviation is unintended.”
>
I would certainly disagree with this notion. There are a variety of
intended deviations. The reason we agreed long ago to call it TTML2 instead
of 1.1 is because we wanted the flexibility to NOT be backwards compatible.

This, for example, is one reason we added 3 new TTML2 specific profiles to
the existing 3 TTML1 profiles. If an implementer wants to create a
processor that effectively has a switch saying whether to follow TTML2 or
TTML1 processing semantics, then they are free to do so. It is up to the
author to effectively mark a document as to which version they wish to have
followed, e.g., by specifying tts:version='1' or not specifying
tts:version, or by telling the processor which regime to use, etc.

The best we can do is give guidance to implementers and authors regarding
how to process or create documents so there is a reasonable likelihood they
will get what they want.

**Comment by palemieux** [comment]
_from https://lists.w3.org/Archives/Public/public-tt/2017Oct/0086.html_

> The best we can do is give guidance to implementers and authors regarding how to process or create documents so there is a reasonable likelihood they will get what they want.

Yes, there will be variations across implementations.

However do you agree that it would be undesirable if, given a document
that contains only TTML1 syntax, a processor was compelled by the
TTML2 specification to process it differently than it would have been
compelled by the TTML1 specification. For instance, wouldn't it be
undesirable if the "associate region" algorithm (which is normative in
both TTML1 and TTML2) would compel an implementation to end-up with a
different associated region given the aforementioned document?

In order words, can't we set the objective to achieving equivalence on
those features that TTML1 and TTML2 have in common, given a document
that contains only TTML1 syntax.

**Comment by nigelmegitt** [comment]
> However do you agree that it would be undesirable if, given a document that contains only TTML1 syntax, a processor was compelled by the TTML2 specification to process it differently than it would have been compelled by the TTML1 specification. For instance, wouldn't it be undesirable if the associate region algorithm (which is normative in both TTML1 and TTML2) would compel an implementation to end-up with a different associated region given the aforementioned document?

I'm not convinced that I do agree here. We found problems with the TTML1 processing semantic when handling edge cases and fixed them (thinking particularly about _associate region_). I think it is reasonable to allow the newer behaviour to be applied bearing in mind that the reason we changed it was because nobody thought the TTML1 behaviour was either a) widely implemented or b) expected.

If we set a rule like this then we freeze all errors in previous specifications in perpetuity. That sounds non-ideal to me, as a general principle.

If what we are saying specifically for _associate region_ is that we would prefer to live with the TTML1 semantics "warts and all" then that's an alternative and different decision, which we could still make. Are there any known examples where the TTML1 behaviour has been used deliberately to hide content?

**Comment by palemieux** [comment]
> If we set a rule like this then we freeze all errors in previous specifications in perpetuity. That sounds non-ideal to me, as a general principle.

@nigelmegitt We addressed these issues in TTML1. What is missing is publishing their resolution as a Third Edition.

**Comment by cconcolato** [comment]
I would propose the following:
In Section 3.4.2 replace:

> A conforming TTML1 content document instance is intended to be a conforming TTML2 content document instance.
> A conforming TTML2 processor should be able to process a TTML1 content document instance; however, it may emit warnings if it encounters deprecated features.

with:

> TTML2 is designed such that:
> - a conforming TTML1 content document instance is a conforming TTML2 content document instance.
> - a conforming TTML1 content document instance not containing any new TTML2 feature would be rendered by a TTML2 presentation processor in an acceptable way, conformant to TTML1, within the variations allowed per TTML1. 
> NOTE: a TTML2 processor may emit warnings if it encounters deprecated features.
> 
> Editor's note: The following features are being investigated:
> - ttp:pixelAspectRatio 
> - tts:direction
> - tts:overflow"

**Comment by skynavga** [comment]
Regarding https://github.com/w3c/ttml2/issues/458#issuecomment-339822234, I do not agree with the proposed rewrite:

1.  the rewrite of the first paragraph substitutes "is" for "is intended to be" is a problem, because the purpose of the first paragraph is to express design intent, and not necessarily the eventual result; furthermore, to establish equivalence ("is"), we would have to do much more work, and I think we cannot declare equivalence a priori, especially since TTML2 is not finalized; for example, we have deprecated a number of features that are not deprecated in TTML1, which some may view as non-equivalence w.r.t. conformance;

2. the rewrite of the second paragraph changes the focus from processing in general to presentation processing in particular, where the original text is intended to address the general case; further, there is nothing more that could be said about presentation processing than is true for generic processing since there are no requirements for presentation equivalence;

3. the rewrite of the second paragraph introduces the vague phrase "in an acceptable way", which is impossible to qualify and, therefore, has no meaning at all; furthermore, it attempts to impose TTML1 semantics on TTML2 processing that may not hold;

4. listing features under investigation serves no purpose whatsoever, as it is not relevant for specification text (or even a note);

5. the best that can be done here, IMO, is adding a note that points out the following:

* TTML1 semantics and TTML2 semantics are not equivalent, and, therefore, processing a TTML1 document as a TTML2 document may produce different results;
* It is possible to construct a TTML Processor that
   * supports only TTML2 semantics
   * supports either TTML2 semantics or TTML1 semantics, with the determination of which semantics applied being out of scope of this specification.

To this end, I will create a PR that adds such a note.

**Comment by cconcolato** [comment]
About 1. 
I think that's a bit problematic that we cannot give any guarantee to the readers. That won't help TTML1 users transition to using TTML2. 

The results of the TTWG discussions seemed to indicate that the differences were marginal. I'm curious what additional work would be needed according to you. 

It would be better I think if we could say that the semantics are the same except for some particular cases, possibly listed explicitly. 

For the fact that TTML1 3rd edition and TTML2 are still being edited, possibly technically, I think we could also simply review that text once the technical edits are done. And anyway, I think maximum compatibility was the intent.

About 2. I proposed that text because people seemed to care only about presentation. Generalizing is good.

About 3. I agree the "in an acceptable way" was not the best wording. The idea was not to impose semantics from TTML1 to TTML2 but give confidence to TTML1 users to transition to TTML2.

About 4. That was not meant to stay in the spec. This was to capture the status of the group's discussion at that time.

About 5. 
About the difference in results, I see your point, but I don't think that's the right way to go, to favor transitions. 
About the fact that one can be build a TTML2-only processor, I don't see the need for that sentence. Anyone doubting that? 
About the fact that one can build a processor that supports both, that's obvious. The question is: what can be shared?
