### ISSUE TITLE
SMPTE backgroundImage annotation.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#460]
A request from SMPTE made on a call today:

In the context of SMPTE-TT being specified as a "safe harbor" format for captions by the FCC, and TTML2 adopting an equivalent semantic of `smpte:backgroundImage`, add an annotation to the effect that the motivation for including image support in TTML2 is at least in part derived from the use of images in SMPTE-TT, and describe the equivalence to `smpte:backgroundImage`.

Note that it may be that the mapping is not from `tts:backgroundImage` but from `<image>` instead. This needs to be checked.

**Comment by palemieux** [comment]
> Note that it may be that the mapping is not from tts:backgroundImage but from <image> instead. This needs to be checked.

Yes. `smpte:backgroundImage` maps most closely to `image`, as it represents content.

**Comment by nigelmegitt** [comment]
@skynavga please respect our conventions on wide review issues. I believe we have WG consensus on the resolution for this, but we have not yet sent a response to the commenter, and as this is a wide review comment, we need to. Reopening.

**Comment by nigelmegitt** [comment]
Apologies to you @skynavga I see that this was an automatic closure driven by merge of the PR containing special text in its message and/or commits. We need to watch out for this in future!

**Comment by skynavga** [comment]
@nigelmegitt please take action and/or close this issue

**Comment by nigelmegitt** [comment]
I have a continuing action on this issue. Reopening.

@skynavga I see you deleted 2 comments made by me 24 days ago, and I've only just noticed that. I don't know right now what was in those comments, but on first glance this seems like poor form - if you think a comment should be deleted, you should contact the commenter and ask them to delete it themselves. Did we discuss it before you deleted them?

**Comment by skynavga** [comment]
@nigelmegitt I don't recall deleting any comments. Since I agree that would be poor form, perhaps there is another explanation.

**Comment by skynavga** [comment]
@nigelmegitt do you need this issue to remain open in order to implement your action item above https://github.com/w3c/ttml2/issues/460#issuecomment-356457580? can't you just send our SMPTE liaison an email from the WG that; it need only be a _draft_ message according to the resolution; I want all WR DoC processing comments closed ASAP

**Comment by nigelmegitt** [comment]
@skynavga yes please leave this open, it's not on your list of things to do.

**Comment by skynavga** [comment]
Give me a date for closing or I will close it.

**Comment by nigelmegitt** [comment]
That would be inappropriate @skynavga , and I would just have to reopen it.

**Comment by skynavga** [comment]
In that case, I object to using a specification development repository to
process WG level issues. You have basically overloaded the ttml2 repo
issues with actions that would have been previously tracked by the W3C
action/issue tracker, and you have not created a specification neutral
repository to hand WG actions. Just give me a date and I'll hold off on
further actions until then. We shouldn't even be having this conversation
since the resolution you are ostensibly keeping this open for is merely to
DRAFT A MESSAGE. You can do that right now, so what is the hold up?

**Comment by nigelmegitt** [comment]
On reviewing this I see that my remaining action was in fact completed on 23rd February, recorded at https://lists.w3.org/Archives/Member/member-tt/2018Feb/0006.html (member only link). Apologies I didn't realise this was already done a long time ago. Closing.
