### ISSUE TITLE
Create CSS mapping for tts:fontShear based on CSS skew

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#471]
This is part of umbrella #406

**Comment by nigelmegitt** [comment]
I believe the proposal is to map to https://www.w3.org/TR/css-transforms-1/#typedef-transform-function using the `skewX()` function when the inline progression direction is the X axis and `skewY()` when it is the Y axis.

The [2017 CSS Snapshot](https://www.w3.org/TR/css-2017/) explicitly allows use of the CSS3 Transforms (Level 1) spec even though it is in WD and has been since 2013, since it has widespread implementation.

**Comment by skynavga** [comment]
Fixed in 924d6cd47f0e36daa5b13fef95c6aa9ac6b88d72.
