### ISSUE TITLE
Remove #ruby-non-nested* features as there is no nesting by definition.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#476]
Can someone point the group to timed text use cases for nested ruby annotations?

The current support for nested ruby annotations complicates specification and implementation.

**Comment by nigelmegitt** [comment]
See also w3c/imsc-vnext-reqs#2

**Comment by skynavga** [comment]
At present, this feature is in the spec, so it will be sorted out by way of whether it gets implemented during CR phase. At present, I know of no one planning to implement it, so it is likely to fall out (and thus will need to be marked at risk).

**Comment by skynavga** [comment]
[RUBY] [1] does not permit nested ruby

>The rt element may contain inline elements or character data as its content, but the ruby element is not allowed as its descendant element.

[1] https://www.w3.org/TR/2001/REC-ruby-20010531/#rt

[HTML5] [2] appears to permit nested ruby, and there are I18N tests that use this construct [3]

[2] https://www.w3.org/TR/html52/
[3] https://www.w3.org/International/tests/repo/run?base=html/semantics/text-level-semantics/the-ruby-element&batch=ruby-html&test=ruby-double-007.html

TTML2 presently does not admit nested ruby, due to the following constraint in 10.2.36:

>if the computed value of tts:ruby is container, then the computed value of tts:ruby of all ancestor elements is none;

therefore, the #ruby and #ruby-full features are already effectively non-nesting, so the features  #ruby-non-nested and #ruby-non-nested-full can be removed (unless we decide to remove the nesting constraint and permit nesting).

I am perfectly comfortable not defining nested ruby support, i.e., leaving in the above constraint. But the WG should take a resolution on this point.
