### ISSUE TITLE
Prune elements whose condition evaluates to false?

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml2#583]
Where are presentation elements pruned if their condition evaluates to false? I propose adding a pruning condition to [construct intermediate document]:

_they are a _presentation related element_ associated with a _condition_ that evaluates to false_

This needs to avoid pruning, say, `style` elements whose condition evaluates to false, because that would break referential styling (a style whose condition is false may reference a style whose condition is true).

To be sure that is the case, we need to modify the term definition of [presentation related element] to explicitly exclude styling elements. This appears to be a harmless change right now.

**Comment by skynavga** [comment]
You cannot prune conditionalized elements since their condition must be evaluated at presentation time, at least for those conditions whose expressions depend on presentation state.

**Comment by nigelmegitt** [comment]
§11.3.1.3 is the section that contains that algorithm and it begins:

> For the purposes of performing presentation processing ...

From which I understand that [construct intermediate document] is part of presentation processing, so it is the time when conditionalized elements need to be pruned.

§8.2.1 condition says:

> The value of a condition attribute must adhere to a `<condition>` expression which is evaluated at the time of presentation processing (lazy evaluation) or prior to the time of presentation processing (eager evaluation), 

@skynavga Are you saying that in some cases conditions are evaluated even later than intermediate document construction? Perhaps we need to elaborate the stages of presentation processing in further detail.

**Comment by skynavga** [comment]
>Are you saying that in some cases conditions are evaluated even later than intermediate document construction?

Yes. This is what I mean presentation time evaluation of a condition. ISD construction precedes presentation processing, which is to say, the input to presentation processing is the ISD(s).

**Comment by nigelmegitt** [comment]
> ISD construction precedes presentation processing, which is to say, the input to presentation processing is the ISD(s)

If this is an important point then we should make sure it is clear in the spec: it is not right now, in fact it appears that the first stage of presentation processing is ISD construction. For the time being I think we do not need an urgent change, but it does seem as though condition evaluation is left somewhat vague. This is hopefully something that can be clarified with more implementation experience.

**Comment by skynavga** [comment]
@nigelmegitt note that conditionalized elements which condition is known to be (and stay) false prior to presentation time could be pruned

**Comment by skynavga** [comment]
@nigelmegitt this raises an interesting question in my mind which is the impact of conditional semantics and its possible affect on timing; say we have a timed span in a sequential container and its condition is dependent on presentation time state; how can we construct an ISD if we don't know if the element's timing will be semantically significant or not? the options I see (at present) are:
* prohibit and ignore timing on a conditionalized element which condition is not fixed at ISD construction time;
* allow and use timing on a conditionalized element which condition is not fixed at ISD construction time, even though its non-timing semantics may be ignored if its condition turns out to be false after ISD construction time;
* require presentation processor to be able to rebuild all ISDs at presentation time;

I am leaning towards the first option. The last option seems impractical, so I rule it out. I could accept the second option; however, its presentation behavior could be non-intuitive (i.e., affect timing but not have a renderable side effect other than influence of timing on other elements).

**Comment by nigelmegitt** [comment]
@skynavga interesting point. Another option would be to state that timings are excluded from the semantics that are excluded by a condition. This means that conditions can be evaluated after ISD construction without timings being modified.

I have seen no use case for modifying timings based on condition evaluation - have you?

**Comment by skynavga** [comment]
@nigelmegitt no I haven't seen a use case, but if it is possible, then someone will try to use it

**Comment by nigelmegitt** [comment]
@skynavga in that case I suggest we do not make it possible!
