### ISSUE TITLE
Remove <animation-value-list> as permissible syntax from <set> definition.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#633]
It looks like the syntax of the animated style property value specified by a `set` element was changed to `<animation-value-list>` at 706f55c1d1f4ddc257eaffa641c475953ca4fc92. This is problematic for the following reasons:

- it expands the syntax in TTML1 without defining a corresponding TTML2 feature
- the expanded syntax is immediately constrained to effectively have the same capabilities as the TTML1 syntax. In other words, processors have to accept a more complex syntax for no benefit
- as discussed at #608, the `<animation-value-list>` currently has fatal problems

Suggest removing the following:

> Style property attributes targeted by an set element are specified directly using attributes in the TT Style namespace or in a namespace that is not some TT Namespace, where the single target animation (key) value adheres to the <animation-value-list> syntax, where each constituent <animation-value> adheres to the syntax of the specified attribute, and where exactly one constituent <animation-value> is specified.
> If more than one constituent <animation-value> is specified, then all constituents other than the first must be ignored for the purpose of presentation processing, and must be considered an error for the purpose of validation processing.

**Comment by skynavga** [comment]
@palemieux 

>it expands the syntax in TTML1 without defining a corresponding TTML2 feature

no, because it requires the animation-value-list to contain a single animation-value

>the expanded syntax is immediately constrained to effectively have the same capabilities as the TTML1 syntax. In other words, processors have to accept a more complex syntax for no benefit

we could fix this by changing "must be ignored" to "should be ignored"; the benefit is greater symmetry and less special-case code

>as discussed at #608, the <animation-value-list> currently has fatal problems

@nigelmegitt is incorrect; there is no fatal problem with the current syntax, and if there is a misunderstanding, it can be easily addressed in a note, on which I will comment further in #608 shortly

**Comment by nigelmegitt** [comment]
I do not understand the benefit to anyone of adding this extra complexity and then immediately constraining it to be the same as it was before. If you want to refactor the way the `<set>` element syntax is defined, why not just reference `<animation-value>` directly? Using `<animation-value-list>` but constraining it to a single entry seems pointless and possibly misleading, since it does not represent the intended syntax.

**Comment by skynavga** [comment]
I am willing to revert the value syntax for ``set`` to ``<animation-value>``, but I am not willing to remove fill and repeat support, nor removing support for multiple styles on one animation (which was agreed to and driven by change proposal 1).

I am also removing "blocks CR", as no justification is given for labeling as such.

**Comment by palemieux** [comment]
> I am also removing "blocks CR", as no justification is given for labeling as such.

I plan to raise a formal objection if `<set>` is not made compatible with TTML1.

**Comment by skynavga** [comment]
OK, but why the label? Just make the objection when the time comes.

**Comment by palemieux** [comment]
> OK, but why the label? 

See email from the chair on 25th January.

**Comment by skynavga** [comment]
@palemieux this is intended to replace the part of #636 that deals with value syntax
