### ISSUE TITLE
Remove @style from set and animate.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#703]
On further consideration, I now have doubts about the utility of adding ``@style`` on ``set`` and ``animate`` elements. In the case of ``set``, the ``@style`` attribute was not supported in TTML1, and, further, only a single style attribute was permitted on ``set`` in TTML1. In TTML2, we now allow multiple style attributes on a single ``set``, but adding ``@style`` seems to go to far, particularly given the disparity with multiple values on ``animate``. In the case of ``animate``, the values of targeted style attributes will consist of multiple values, i.e., as ``<animation-value-list>`` expressions. While it is straightforward to recognize the possibility of multiple values on a style attribute that appears directly on an ``animate`` element, it is not at all straightforward to support multiple values on an attribute that appears on a ``style`` element directly or indirectly referenced via ``@style`` on ``animate``. In this case, we would have some ``style`` elements with multiple value styles (for reference by ``animate`` elements) and others with single value styles (for reference by other content and ``set`` elements).

I propose that we back out the addition of ``@style`` on ``set`` and remove it from ``animate``. This will significantly reduce the complexity of implementations of animation elements without impacting functionality, since one can directly specify animated attributes on ``set`` and ``animate`` without use of ``@style``.

**Comment by nigelmegitt** [comment]
> it is not at all straightforward to support multiple values on an attribute that appears on a `style` element directly or indirectly referenced via `@style` on `animate`

I don't understand this - surely a value list on a styling attribute in a `style` element would not and should not be valid? As far as I can tell the only place where value lists are conformant is in the context of an `animate` element. Perhaps the problem introduced here is the `<animation-value-list>` syntax rather than the referential styling?

**Comment by skynavga** [comment]
@nigelmegitt exactly, which is why it makes having ``@style`` on ``animate`` completely broken or non-usable, and, for symmetry, should apply to ``set`` as well;

**Comment by nigelmegitt** [comment]
@skynavga Okay, let's flip this round for the purpose of devil's advocacy: isn't specifying a `@style` reference on an `animate` element the same as specifying for each style property specified by the referenced style(s) an `<animation-value-list>` with a single value? There doesn't seem to be any prohibition on an inline styling attribute on `animate` that has a single value in its "list", so why would there be a problem? 

Otherwise why not constrain `<animation-value-list>` to have at least 2 values?

**Comment by nigelmegitt** [comment]
@skynavga OK if you do that then it's consistent to remove use of `@style` from `animate`, and there's a good rationale I think. If referential styling for animation is ever needed I guess we could introduce a new element under `<styling>` that would be analogous to `<style>` but whose attribute values must contain `<animation-value-list>`s. I don't see an immediate need for that.

**Comment by nigelmegitt** [comment]
Discussed in the context of #707.
