### ISSUE TITLE
Incorrect description of tts:position example.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#712]
The bottom of the region seems to be positioned `10% * (root container region height)` from the bottom of the root container region.

This is inconsistent with the clause _percentage value component for a vertical position offset is relative to the height of the positioning rectangle minus the height of the associated region._

**Comment by palemieux** [comment]
See test and renders at https://github.com/w3c/imsc-tests/pull/49

**Comment by skynavga** [comment]
OK, I verified that both offset and edge position calculations are the same. See https://codepen.io/skynavga/pen/BxVrRj. I will update the description of the example. I think we don't need to actually change the image since one can't really (visually) discern what offset appears in the image, and the image is intended to only be representative.
