### ISSUE TITLE
Applicability of tts:rubyPosition and tts:rubyAlign.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#717]
The `tts:rubyPosition` attribute applies to "span only if the computed value of tts:ruby is container". IMO this does not really make sense, as the ruby container is just a general container for text with ruby annotations (it may work though in the simple ruby case).

The `tt:span` that is actually affected corresponds to the ruby text content or instead (if present) the ruby text container. So the attribute should instead apply to a `tt:span` only if the value of `tts:ruby` is `text` (only in case `tt:span` is not a child of a ruby text container - as all ruby text content of the same ruby text container shall have the same position) or `textContainer`.

The current wording also does not work if double-sided ruby is used, as when relevant on the ruby container only, it would not be possible to specify the (different) positions in case _two_ text containers are present. The [double-sided ruby example next to the definition of `tts:ruby`](https://w3c.github.io/ttml2/#style-attribute-ruby) is a good example for this issue. It uses `tts:rubyPosition` on ruby text container level - where it cannot be applied according to the current wording.

**Comment by skynavga** [comment]
In reviewing the current text and comparing with [CSS Ruby Layout Module Level 1](https://drafts.csswg.org/css-ruby-1/), I have concluded that ruby position semantically applies only to Ruby Text Content (`tts:ruby="text"). However, since it is inheritable, then an author can specify it on any descendant, including Ruby Text Container, Ruby Container, paragraph, etc. I will change the applies row of the syntax table accordingly.

I have also reviewed ruby align semantics, and there are two options here: (1) to take the approach of the above cited CSS Ruby Module and state that alignment semantics applies (collectively) to Ruby Base Container, Ruby Base, Ruby Text Container, and Ruby Text; or, alternatively, (2) state that alignment semantics apply to Ruby Container as a whole, which includes alignment of its constituent areas. At present, we already do this (in the applies row of the syntax table), but we don't elaborate the meaning of this. Therefore, I will add a note that elaborates this point.

**Comment by palemieux** [comment]
>then an author can specify it on any descendant

_ancestor_, right?

**Comment by skynavga** [comment]
@palemieux I edited my comment, so that text is no longer present. See the just posted PR (#740).

**Comment by palemieux** [comment]
> syntactically speaking, we may have Ruby Text Content that is not enclosed in a syntactically explicit span with tts:ruby="textContainer"

What is the use case for this? It significantly complicates processing.

> I have also reviewed ruby align semantics, and there are two options here:

The two options yield identical results, right? In other words, applying tts:rubyAlign="center" to the container is identical to applying tts:rubyAlign="center" to each of its text, base, baseContainer and textContainer elements.
