### ISSUE TITLE
Direction of tts:textShadow depends on writing direction.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#723]
The direction of the shadows specified by tts:textShadow currently depends on the [writing direction]( https://www.w3.org/TR/ttml2/#style-value-shadow):

>The first <length> term denotes the offset in the inline progression direction of the associated area [...], the second <length> term denotes the offset in the block progression direction of the associated area

This means that, given the style declaration `tts:textShadow="10% 10% white"`, the shadow will appear to the bottom right of `rltb` text and to the bottom left of `tbrl` text.

I would think this is visually inconsistent. It also diverges from CSS (#722), and requires writing direction to be propagated during style computation.

![textshadow](https://user-images.githubusercontent.com/4871350/39550102-041342cc-4e15-11e8-8868-21f500378ef2.png)

**Comment by skynavga** [comment]
I do not believe it is inconsistent. Indeed, I find your example of being independent from writing mode to be inconsistent (because it puts the shadow in the direction of the before edge rather than the after edge on the CJK characters.

I believe the problem is that you are attempting to interpret this feature as an image processing feature when it is in fact a typographic feature. It is, for example, not related to the notion of a single light source illuminating the root container, but is, instead, defined and intended to be use like a font style, such as italic or weight.

I'm not saying that an image processing based feature is not worth considering; rather, it is simply not the intent of this particular style property feature.

**Comment by skynavga** [comment]
@palemieux regarding

>requires writing direction to be propagated during style computation

you seem to imply that this is not (already) required! but it is required for a multitude of reasons of which this is only one example

**Comment by palemieux** [comment]
> you seem to imply that this is not (already) required! but it is required for a multitude of reasons of which this is only one example

Yes... and it is awkward.

**Comment by palemieux** [comment]
> I believe the problem is that you are attempting to interpret this feature as an image processing feature when it is in fact a typographic feature.

I am arguing that the current is counter-intuitive to authors, and therefore could be improved.

**Comment by skynavga** [comment]
@palemieux however, if we did as you suggest, this would be a *special case* that would have an impact on both implementers and authors. It would be a special case because other uses of directionality in similar contexts are writing mode relative, e.g., the interpretation of border (radii) is not with respect to left, right, top, bottom, but with start, end, before, after; in other words, setting border after would have the same "inconsistency" you wish to avoid; personally, I think making an exception for this property creates rather than reduces cognitive dissonance and leads to (rather than prevents) authorial errors.

**Comment by palemieux** [comment]
See https://www.w3.org/TR/2006/REC-xsl11-20061205/#text-shadow for the XSL definition, which does not seem to be dependent on writing direction.
