### ISSUE TITLE
Remove animation from tts:ruby.

### ISSUE THREAD

**Issue by spoeschel** [w3c/ttml2#773]
The `tts:ruby` attribute is used to reflect the hierarchy of the different ruby elements (`ruby`, `rb` etc.) from the [Ruby Annotation spec](https://www.w3.org/TR/2001/REC-ruby-20010531/) while keeping the present TTML content element hierarchy, as the attribute is always applied to `tt:span`. The attribute is used to express a fixed relation between different parent/children/neighbour nodes. So in my opinion it is not feasible to flag this attribute as animatable, as the position within the ruby hierarchy is always fixed.

The only decent meaningful case I could think of is a discrete animation whereby the `tts:ruby` value of a ruby container and all of its children is changed from the respective original value to `none` at the same time. However I can't see why anyone would want to do that.

So I propose to make `tts:ruby` non-animatable.

**Comment by skynavga** [comment]
My first reaction on reading this was that all styles are currently animatiable, at least on a discrete basis, and, therefore, so should `tts:ruby`. However, on further consideration, I believe you are correct, primarily because this property is so closely related (and constrains and is constrained by) other content marked with this attribute in its local context. Changing one would most likely require changing others at the same time, and there just doesn't seem to be a use case for this facility.

Therefore, I will create a PR that does as you suggest.
