### ISSUE TITLE
Implied region animation ambiguity.

### ISSUE THREAD

**Issue by cconcolato** [w3c/ttml2#820]
According to https://w3c.github.io/ttml2/#layout-vocabulary-region-special-inline-animation-semantics, if you specify tts:extent on a `p` the behavior is as if an animation had been created. The text also says:
>if multiple animation elements (Ai, ..., Aj) already apply to R, then A applies subsequent to these the last of these existing animations, namely, immediately after Aj.

Aside from the typo ("to these the last" - > "to the last"), it is not clear what happens if two `p` have the same begin/end and refer to the same region but also use two different extent attributes. 

One ambiguous point is the order following which the animations are added. Is it document order? I would think so but it is not so clear.

The second ambiguous point is: how to apply the two animations? The text says "subsequent" which would not make sense because the paragraphs will not be active once the first animation is done, so the subsequent animation will never have any effect. SMIL defines the `additive` attribute to resolve this case and the default value is `replace`, meaning that in this case the last paragraph in document order sets the extent of the single region used by both paragraph. 

Of course, this is assuming that there is only one region being processed, that the animations don't create temporary regions.

**Comment by nigelmegitt** [comment]
> Is it document order?

Yes, it should be.

I agree the implication is the use of `additive`. 

> assuming that there is only one region being processed

The animations cannot create temporary regions, there's no mechanism for that. We also had a lively discussion some time ago (sorry no time for archaeology right now, but it was in the GitHub era) about whether or not any given `div` or `p` could be flowed into more than one region simultaneously. I can't actually remember the answer. The example was something like:

```xml
<div xml:id="weirdDiv">
   <p>Where does this text go?</p>
   <div region="r1"><p>Some text in region r1</p></div>
   <div region="r2"><p>Some text in region r2</p></div>
</div>
```

so I guess your question is what happens if `weirdDiv` has `tts:extent` or `tts:position` attributes on it?

**Comment by cconcolato** [comment]
> Yes, it should be.
> 
> I agree the implication is the use of additive.

Fine.

> I guess your question is ...

You're going beyond my question. In your example, I would think that the animations are created after the div is reparented into the regions.

**Comment by nigelmegitt** [comment]
OK seems like we just want to change to additive then.

**Comment by skynavga** [comment]
I need to look at this more carefully, but I am probably not going to agree to it being additive (for complexity reasons).

**Comment by skynavga** [comment]
@cconcolato @nigelmegitt it turns out that the question of additive vs replace semantics is moot, since replace behavior is already explicit via step (5), [animation styling] of [Specified Style Set Processing](file:///Users/glenn/work/ttml2/spec/ttml2.html#semantics-style-resolution-processing-sss).

**Comment by skynavga** [comment]
Merged early per WG resolution.
