### ISSUE TITLE
Can line areas intersect with line stacking strategy "line height"?

### ISSUE THREAD

**Issue by tairt** [w3c/ttml2#859]
[Section 11.3.2.2 - Line Stacking Strategy]( https://w3c.github.io/ttml2/index.html#semantics-line-stacking)

* > when the computed value of tts:lineHeight of a paragraph is a specified <length>, then the line areas of a paragraph exactly abut one another but their content may (1) consume less space in the block progression dimension than required to fit its content, in which case that content may intersect with the preceding line area of that paragraph or (2) consume more space in the block progression dimension than required to fit its content.

a) The text is difficult to read and seems to be circular:  When content consumes less space in a line area then needed to fit into that  line-area one consequence could be that it consumes more space than needed to fit in that line area?

b) I can't really see a case where content exceeds the line area. Can someone give an example?

**Comment by tairt** [comment]
@skynavga provided an example in https://github.com/w3c/ttml2/pull/825

> @tairt regarding your last question, here is an example on Chrome; since XSL-FO line-height stacking strategy matches (or at least is supposed to match) CSS, then such results are indeed possible:

![grafik](https://user-images.githubusercontent.com/4597762/41860916-20cfeaa4-78a0-11e8-94bf-4d5b87589671.png)

**Comment by tairt** [comment]
@skynavga Can you provide the corresponding TTML for this?

I don't think that CSS is the primer reference here. The reference is the specification text in XSL-FO, especially section 4.5 of XSL 1.1 (https://www.w3.org/TR/xsl11/#area-line)

From the text in XSL 1.1 content of line areas should not intersect. 

If there is a case the conditions needs to be explained.

**Comment by skynavga** [comment]
The reason that line areas may intersect is described as follows:

The computed value of `tts:lineHeight` is used to compute the half leading included in the computation of the _bpd_ dimension of a **expanded-nominal-line-rectangle**, which serves as a minimum line area height for a paragraph.

Likewise, `tts:lineHeight` is effectively inherited by each inline child (spans and anonymous spans), and used to compute the half leading included in the computation of the _bpd_ dimension of the **expanded-rectangle** of the generated inline areas. [This inheritance is part of both XSL-FO and CSS semantics, which match in this respect.]

Since `tts:lineHeight` may be an explicit dimension that is smaller than the text-altitude + text-depth of any inline area, then, to cite the language found in CSS2 §10.8.1 [1]:

>When the 'line-height' value is less than the font size, the final inline box height will be less than the font size and the rendered glyphs will "bleed" outside the box. If such a box touches the edge of a line box, the rendered glyphs will also "bleed" into the adjacent line box.

[1]  https://www.w3.org/TR/2008/REC-CSS2-20080411/visudet.html#q22

See also https://github.com/w3c/ttml2/issues/858#issuecomment-400188498 in #858, where we show how the half leading of line areas and inline areas may be different and may be negative.

**Comment by tairt** [comment]
Our reference is XSL-FO. Here it states in chapeter 4.5

> The expanded-rectangle of an inline-area is the rectangle with start-edge and end-edge coincident with those of its allocation-rectangle, and whose before-edge and after-edge are **outside** those of its allocation-rectangle by a distance equal to either  (a.) the half-leading ...

My interpretation is that the the expanded rectangle is never inside the allocation rectangle, it always outside.

**Comment by tairt** [comment]
@skynavga Regarding the picture you added: can you provide the corresponding TTML for it?

**Comment by skynavga** [comment]
@tairt it is not sufficient to refer only to the literal words of XSL-FO, since XSL-FO is built on CSS2 and claims to comply with CSS2 in this regards; in particular, your interpretation of **outside** is not consistent with the fact that half-leading may be negative

**Comment by skynavga** [comment]
@tairt could you propose a spec change or close this issue please

**Comment by tairt** [comment]
I close this issue, because there is a time tight timeline for publication and also because the text is not normative.

My view is that the complete chapter about line stacking should be removed. It does not clarify calculation of line-height and how lines are stacked. For explanation XSL-FO concepts are used and then for important parts some conclusions are inferred from CSS. 

Examples and guidelines how to specify line height and font size would be helpful.

**Comment by skynavga** [comment]
Thanks. We disagree on the utility of this information. If you could point out something here that is factually incorrect, they we could correct or remove that part. For my part, I believe this information is very useful because it clarifies ambiguities in XSL-FO and CSS. I agree that the inclusion of further examples in this section would be useful, however, and we can add such examples up until September 25 or the time that we have to complete the PR version of this spec. Perhaps you would like to contribute or work on such examples?
