### ISSUE TITLE
Clarify that [validate document] may produce false positive results.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#876]
Add note under §5.3.1.2 [validate document] that, since the effective validation schemas are implementation dependent, false positive results may occur. In particular, describe false positive example where the use of `prohibited` in a content profile does not necessarily lead to a validation error in the case that a prohibited feature is used in a document but the effective validation schemas are overly general in their definition.

**Comment by nigelmegitt** [comment]
Isn't this dependent on the type of schema being used? There's already a note under **[construct effective validation schemas]** that the schema types are not defined by the TTML spec. Given that, the strongest note I think we should make is that implementers and users should be aware that different schema types offer differing levels of specificity when used for validation processing, and that therefore the users should be aware that this can lead to false results. I don't want to get into the situation where we list or assume particular kinds of schema.

**Comment by skynavga** [comment]
@nigelmegitt yes, and that is the point of this clarification; see also the first note under the prologue of 4.1

**Comment by nigelmegitt** [comment]
@skynavga I'm concerned that the note seems to be a comment on the quality of the implementation and is therefore out of scope. As you say, the note in 4.1 mentions that RNC and XSD schemas are not always sufficient for 100% accurate results. I don't think we need any more, especially because it is already stated that the schemas mentioned in §5.3 are undefined. You may as well add a note that "undefined stuff has an undefined behaviour", but that would be equally unhelpful.

**Comment by skynavga** [comment]
@nigelmegitt notes can contain anything we want, we have plenty of notes that read on the quality of the implementation;  unless a note is factually wrong or misleading, then it is fair to include it if it provides useful advisory information; in this case, it is addressing a possible reader expectation about what [validate document] is required to do, and explicitly sets a low bar for that mark

**Comment by skynavga** [comment]
Merged early per WG resolution to move forward with CR3 CfC.
