### ISSUE TITLE
Change TTML1 normative reference to TTML1 3ED.

### ISSUE THREAD

**Issue by palemieux** [w3c/ttml2#884]
The TTML1 3ED prose matches that of TTML2 for those capabilities they have in common. In contrast, there is divergence between TTML1 2ED and TTML2 for the same capabilities.

**Comment by skynavga** [comment]
I'm concerned that this change must be labeled as a substantive change, which would trigger yet one more CR(3), thus delaying TTML2 even further.

**Comment by nigelmegitt** [comment]
I'm not sure about that @skynavga but I think it is important that we make the change, and it was clearly our long-standing intention in doing the work on TTML1 Third Edition.

As a (weak) data point, IMSC 1.1 references TTML1 Third Edition (informatively) as well as TTML2 (normatively).

**Comment by skynavga** [comment]
@nigelmegitt I agree that was our intention, but at the same time, we have agreed to no more substantive changes. If TTML1 3e were a non-substantive update to TTML1 2e, there would be no question in my mind; however, 3e is a substantial update, so updating our normative reference makes that update substantive. On the other hand, one could argue that the 3e changes come from TTML2 so that the final effect is a no-op. Then again, for example, we define `#lineHeight` in TTML2 based (currently) on TTML1 2e, and changing the reference to 3e would make that definition change (to become compatible with TTML2 semantics, in fact). In any case, I believe one may reasonably argue either way on this point, so we need to take care. If there is an objection to an update based on it being considered substantive, then we would have to back out such change.

**Comment by nigelmegitt** [comment]
>  If there is an objection to an update based on it being considered substantive, then we would have to back out such change.

Bear in mind that there may alternatively be an objection to proceeding _without_ updating the reference, in which case we may have to adjust our timelines.

**Comment by skynavga** [comment]
Taking a conservative position, I am labeling this as a substantive change.

**Comment by skynavga** [comment]
Merged early per WG resolution to move to CR3 CfC.
