### ISSUE TITLE
Specify date as well as hours, minutes and seconds in time expressions

### ISSUE THREAD

**Issue by plehegar** [w3c/ttml2#96]
Proposal from EBU to permit date to be specified in time expressions, optionally. Purpose of this is to allow 24 hour clock times to be used without ambiguity at midnight crossing. Also to permit second-accurate duration calculations by allowing externally managed reference of dates that include leap seconds.

An implementation may usefully allow dates to be inferred or inherited from a reference element rather than requiring the same date on every begin and end attribute where date semantics are needed.

(raised by Nigel Megitt on 2013-10-31)
From tracker issue http://www.w3.org/AudioVideo/TT/tracker/issues/293

**Comment by skynavga** [comment]
Lacking a hard requirement and draft specification text, I am marking this for ttml.next and closing. If there is a hard requirement here, please draft specification text and reopen.

**Comment by nigelmegitt** [comment]
There is a clear and hard requirement here. Consider a midnight crossing example (or is it?):

```xml
<tt ttp:timeBase="clock" ttp:clockMode="utc">
...
<p begin="23:59:58" end="00:00:01">[content here]</p>
...
</tt>
```

Comparison of the two time expressions reveals that the end of the `p` is earlier than its begin, therefore it never becomes active. There is no conformant way to discern this is happening using clock-time expressions - only offset-time expressions have some hope of doing so, and even then the epoch (time zero) is poorly defined.

The request in this issue is to allow for a date component to be added to clock-time expressions.

**Comment by nigelmegitt** [comment]
[Meeting 2016-03-16] Group just about agrees to adopt the date format specified in SMIL when `ttp:timeBase="clock"` - see https://www.w3.org/TR/smil/smil-timing.html#Timing-WallclockSyncValueSyntax - it is based in part on ISO8601 and allows a year-month-day expression to precede the time value.

**Comment by nigelmegitt** [comment]
Meeting 2017-05-18: Discussion about timezone addition to time expressions; majority view against doing so since UTC can be used instead. I take action to propose wording to clarify the intended meaning of `clockMode="local"` as being undefined with respect to UTC and intended to be "whatever time this is where you are".

**Comment by skynavga** [comment]
Add clarifying notes in c36dffb71744a489372fe6a86ab303dc2f258a5d, which closes the outstanding comments.
