### ISSUE TITLE
Sourced data embedding should include the use of @src as well as nested <source>.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#986]
The definition of "sourced data embedding" and the language describing the content models for `data` do not cover the use of `@src` as opposed to using a nested `source` element; however, other language in `data` clearly sanctions such usage.

This can be resolved by the following in 9.1.3 to cover the use of `@src` as well:

>(3) zero or more elements in the Metadata.class element group followed by one or more source elements

**Comment by palemieux** [comment]
The definition _sourced data embedding_ would need to change.

The following prose would also need to change: _When sourced data embedding is used, the data resource is obtained from the first resolvable child source element._

It might be easier to introduce a new term, which perhaps could be done editorially now since the specification does not prohibit the use of `@src` without children elements.

**Comment by skynavga** [comment]
No longer applicable due to https://github.com/w3c/ttml2/pull/1132 and https://github.com/w3c/ttml2/pull/1143. In particular, the use of `@src` now falls under _reference data embedding_.
