### ISSUE TITLE
Back out requirement for xml:id on out-of-line region.

### ISSUE THREAD

**Issue by skynavga** [w3c/ttml2#989]
The following in 11.1.2 inadvertently invalidates valid TTML1 content where this constraint did not appear. Suggest changing 'must' to 'should'.

>An out-of-line `region` element must specify an `xml:id` attribute.

Note that there is no harm in having an out-of-line region without an ID. It just means that no `@region` attribute can reference it. So, while such usage is inefficient, it doesn't break anything.

**Comment by nigelmegitt** [comment]
I agree with the intent here, i.e. I think this was an unintended error, but I am concerned that it's a substantive change that could be difficult to get through to PR directly since we have no "at risk" feature with which to link it. In particular, it's dealing with an edge case of TTML1 content that I've never actually seen, and which we perhaps ought to be deprecating in any case.

As an alternative, we could note this constraint informatively in [§3.4.2 Backward Compatibility](https://www.w3.org/TR/ttml2/#compatibility-backward), and maybe even add a recommendation for implementers to deal with this constraint in a deliberately lax way because it is possible that TTML1 documents will not have the `//region@xml:id` attribute in all cases.

**Comment by skynavga** [comment]
This is marked for 2E milestone, so we don't need to do anything now.

**Comment by nigelmegitt** [comment]
Thanks @skynavga I hadn't noticed that when I made https://github.com/w3c/ttml2/issues/989#issuecomment-419837625

**Comment by skynavga** [comment]
Leave _must_ language in place, but add qualification that this constraint applies when the `region` element is referenced by a `@region` attribute. Add similar qualification to the same language appearing under `animate` and `set` w.r.t. out-of-line animations.

**Comment by skynavga** [comment]
Downgrading this to an editorial change since the additional qualifications are what was intended in the first place, and, furthermore, there is no constraint in TTML1 that unreferenced `region`, `animate`, or `set` must have `xml:id`. Finally, there are already many uses of out-of-line `region`, `animate`, and `set` in [ttml2-tests](https://github.com/w3c/ttml2-tests) that do not specify `xml:id`.

**Comment by skynavga** [comment]
Note that an alternative approach is simply to remove the constraint entirely, since, by definition, one can't have a `region` or (`animate`|`set`) element that is referenced by `@region` or `@animate` unless the element has `xml:id` in the first place. So the constraint turns out to be entirely redundant. If someone prefers this option, I will happily switch to using it.

**Comment by nigelmegitt** [comment]
I see that the change proposed would modify the absence or presence of a default region. Currently:

```xml
<tt>
   <head>
      <layout>
         <region/>
      </layout>
    </head>
</tt>
```

has a default region because it has no out-of-line regions, because the region specified has no `xml:id` and therefore is not an out-of-line region.

If we remove the constraint that out-of-line regions must have an `xml:id` then the region presumably does qualify as being out-of-line and there is no longer any default region available.

That in turn modifies the conformance of a presentation processor, making the change substantive.

**Comment by skynavga** [comment]
In reviewing the language re: default region in TTML1 §9.3.1 and TTML2 §11.3.1.1, the requirement that an `xml:id` be specified (in TTML2) clearly breaks TTML1 compatibility. For example, in TTML1

```
<layout>
  <region/>
</layout>
```

would prevent the creation of an implied default region, and, since no `xml:id` is present, no content element could refer to that region either, resulting in a document that may have content but no region with which it associated.

Perhaps that should have been ruled out in TTML1, but it wasn't. Off hand, I can't think of a reason why an author would want to do this. Nevertheless, that's how things stand in TTML1.

When I introduced the out-of-line region concept in TTML2, I really intended that any `region` child of `layout` be an out-of-line region, which model holds for `Animation.class` children of `animation` as well.

I believe I added the language to [out-of-line region]

>and specifies an xml:id attribute which value is referenced by a region attribute on the associated element to be selected into the region

and to [out-of-line animation]

>and specifies an xml:id attribute which value is referenced by an animate attribute on the associated element to be animated

as a mere consequence of the presence of the language that is proposed to be removed from the definitions of `region`, `animate`, and `set`, and not for any other technical reason.

In particular, I do not believe I intended a `region` in `layout` or an `Animation.class` child of `animation` to ever NOT be considered as an out-of-line region (animation), regardless of the presence or absence of `xml:id`.

I will remove the above language from these definitions (so as not to be inconsistent with our removing the requirement for `xml:id` to be present under the element definition), and relabel this as substantive for semantics.

I believe I can create both validation and presentation tests as well.
